image: ubuntu-latest

options:
  # Adding as a safety catch
  max-time: 30

definitions:
  steps:
    - step: &Test
        name: Test
        image: ruby:2.7.8
        script:
          - bundle install
          - rspec

pipelines:
  branches:
    main:
      - step: *Test
  pull-requests:
    main:
      - step: *Test
